FROM node:20-alpine AS builder

ENV NODE_OPTIONS="--max-old-space-size=8192"

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

EXPOSE 4200

CMD ["npm", "start", "--", "--host", "0.0.0.0"]